### ISSUE TITLE
Vehicle

### ISSUE THREAD

**Issue by Shruti2791** [ganisivakumar/ruby_tutorial#8]
1) Style guide issues !!
2) There is no use of #change_price=. Ruby does not assign attributes like this. Read about it.
3) Read about #to_s. This helps in displaying objects.

**Comment by ganisivakumar** [comment]
Fixed style guide issues(space around operators)
Removed method "change_price"
Added to_s method to display objects.

**Comment by Shruti2791** [comment]
1) Style guide issues.
2) #change_price still exists. Moreover this behaviour should be a part of Vehicle class because price is a feature of vehicle not bike.
3) Keep one line difference between methods.

**Comment by ganisivakumar** [comment]
I got what i am doing wrong in change_price method,thanks.
What are the style guide errors,please show me the line.

**Comment by Shruti2791** [comment]
Cool, the attr_accessor thing works :+1: 
2) There should be a space
- after commas
- after attr_reader

**Comment by ganisivakumar** [comment]
Thanks, got the style guide errors i am doing.I modified them.please review it 
https://github.com/ganisivakumar/ruby_tutorial/blob/master/vehicle/lib/bike.rb
https://github.com/ganisivakumar/ruby_tutorial/blob/master/vehicle/lib/vehicle.rb

**Comment by Shruti2791** [comment]
Cool :+1: 
Next time the styling issues won't be pointed, you will have to mind them yourself.
Can we pass named parameters instead of positioned ones ? For eg: initialize(name, price, dealer) expects the first parameter to be name and second to be price and so on. Is it possible to not depend upon the positioning of the parameters ?
